eureka:
  client:
    service-url:
      defaultZone: http://192.168.6.13:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service