eureka:
  client:
    service-url:
      defaultZone: http://192.168.6.13:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://192.168.6.13:9411
  sleuth:
    sampler:
      percentage: 1.0